language: node_js
node_js:
    - "5.8"
before_script:
    - npm install
script:
    - gulp test

notifications:
    on_success: never
    on_failure: never

# script: node_modules/karma/bin/karma start my.conf.js --single-run
# before_install:
#     - export DISPLAY=:99.0
#     - sh -e /etc/init.d/xvfb start
# before_script:
#     - npm install